application: prealfaws
version: 2
runtime: python
api_version: 1

handlers:
- url: /static/
  static_dir: static
- url: /tipet/
  script: tipet.py
- url: /blog/admin
  script: /blog/admin.py
- url: /blog/.*
  script: /blog/dynamic.py
- url: /me/.*
  script: me.py
- url: /fbm/.*
  script: /fbm/handle.py
- url: /.*
  script: main.py
